# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lights.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lights.proto',
  package='light',
  syntax='proto3',
  serialized_options=b'\n\005lightB\020LightServiceImplP\001',
  serialized_pb=b'\n\x0clights.proto\x12\x05light\"\x16\n\x05Power\x12\r\n\x05state\x18\x01 \x01(\x08\"\x18\n\x06\x43olour\x12\x0e\n\x06\x63olour\x18\x01 \x01(\t2g\n\x0cLightService\x12\'\n\x07powerOn\x12\x0c.light.Power\x1a\x0c.light.Power\"\x00\x12.\n\x0c\x63hangeColour\x12\r.light.Colour\x1a\r.light.Colour\"\x00\x42\x1b\n\x05lightB\x10LightServiceImplP\x01\x62\x06proto3'
)




_POWER = _descriptor.Descriptor(
  name='Power',
  full_name='light.Power',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='light.Power.state', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=45,
)


_COLOUR = _descriptor.Descriptor(
  name='Colour',
  full_name='light.Colour',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='colour', full_name='light.Colour.colour', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['Power'] = _POWER
DESCRIPTOR.message_types_by_name['Colour'] = _COLOUR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Power = _reflection.GeneratedProtocolMessageType('Power', (_message.Message,), {
  'DESCRIPTOR' : _POWER,
  '__module__' : 'lights_pb2'
  # @@protoc_insertion_point(class_scope:light.Power)
  })
_sym_db.RegisterMessage(Power)

Colour = _reflection.GeneratedProtocolMessageType('Colour', (_message.Message,), {
  'DESCRIPTOR' : _COLOUR,
  '__module__' : 'lights_pb2'
  # @@protoc_insertion_point(class_scope:light.Colour)
  })
_sym_db.RegisterMessage(Colour)


DESCRIPTOR._options = None

_LIGHTSERVICE = _descriptor.ServiceDescriptor(
  name='LightService',
  full_name='light.LightService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=73,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='powerOn',
    full_name='light.LightService.powerOn',
    index=0,
    containing_service=None,
    input_type=_POWER,
    output_type=_POWER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='changeColour',
    full_name='light.LightService.changeColour',
    index=1,
    containing_service=None,
    input_type=_COLOUR,
    output_type=_COLOUR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LIGHTSERVICE)

DESCRIPTOR.services_by_name['LightService'] = _LIGHTSERVICE

# @@protoc_insertion_point(module_scope)
